baseURL = "https://example.org/"
languageCode = "en-us"
title = "Alex Haslam"
theme = "PaperMod"
enableEmoji = true

[params.profileMode]
enabled = true
title = "Alex Haslam"
subtitle = "Simulation and ML Engineer"
imageUrl = "/images/profile.png"
imageWidth = 120
imageHeight = 120

[params.assets]
favicon =  "/favicons/favicon.ico"
favicon16x16 =  "/favicons/favicon-16x16.png"
favicon32x32 =  "/favicons/favicon-32x32.png"
apple_touch_icon =  "/favicons/apple-touch-icon.png"

[[params.socialIcons]]
name = "GitHub"
url = "https://github.com/alxhslm"

[[params.socialIcons]]
name = "LinkedIn"
url = "https://www.linkedin.com/in/alexanderhaslam"

[[params.socialIcons]]
name = "GoogleScholar"
url = "https://scholar.google.com/citations?user=XIvQ5NYAAAAJ&hl=en"

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 10

[[menu.main]]
identifier = "projects"
name = "Projects"
url = "/projects/"
weight = 10

